{
    'name': 'Utility Core',
    'version': '18.0.1.0.1',
    'category': 'Utility ERP',
    'summary': 'Core Master Data for Utility ERP Platform',
    'description': """
Enterprise Utility Core Module
===============================
Master data management for national electricity distribution companies.
Manages customers, accounts, meters, tariffs, and network infrastructure.

Models: Company, Region, Area, Zone, Office, Feeder, Substation,
Transformer, Route, Customer, Account, Connection, Meter, Tariff, Staff, Team,
User Role.
    """,
    'author': 'Utility ERP Platform',
    'website': 'https://www.utility-erp.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'contacts', 'account', 'date_range', 'sale', 'payment'],
    'data': [
        'security/utility_security.xml',
        'security/ir.model.access.csv',
        'data/utility_sequence.xml',
        'data/utility_date_range_type_data.xml',
        'data/utility_user_role_data.xml',
        'data/utility_meter_type_data.xml',
        'data/utility_meter_status_data.xml',
        'data/utility_subscriber_data.xml',
        'data/utility_region_data.xml',
        'data/utility_team_data.xml',
        'data/utility_config_data.xml',
        'data/utility_product_data.xml',
        'data/utility_pricelist_data.xml',
        'data/utility_block_tariff_config_data.xml',
        'data/utility_contract_template_com_data.xml',
        'data/utility_contract_template_tm1_tpm1_data.xml',
        'data/utility_contract_template_gov_large_mosque_data.xml',
        'data/utility_sale_order_type_data.xml',
        'data/utility_migration_mapping_data.xml',
        'data/utility_meter_cron.xml',
        'data/utility_cron_management_data.xml',
        'data/utility_workflow_cron.xml',
        'views/utility_root_menu.xml',
        'views/utility_block_tariff_config_views.xml',
        'views/utility_region_views.xml',
        'views/utility_office_views.xml',
        'views/utility_feeder_views.xml',
        'views/utility_substation_views.xml',
        'views/utility_transformer_views.xml',
        'views/utility_meter_reader_views.xml',
        'views/utility_route_views.xml',
        'views/utility_customer_views.xml',
        'views/utility_customer_lifecycle_views.xml',

        'views/utility_connection_views.xml',
        'views/utility_connection_type_views.xml',
        'views/utility_meter_log_views.xml',
        'views/utility_meter_views.xml',
        'views/utility_meter_type_views.xml',
        'views/utility_meter_model_views.xml',
        'views/utility_meter_status_views.xml',

        'views/utility_staff_views.xml',
        'views/utility_team_views.xml',
        'views/utility_user_role_views.xml',
        'views/utility_meter_replacement_views.xml',
        'wizards/views/utility_customer_wizard_views.xml',
        'wizards/views/utility_customer_lifecycle_wizard_views.xml',
        'wizards/views/utility_upgrade_validation_wizard_views.xml',

        'views/utility_customer_menu.xml',
        'views/utility_network_menu.xml',
        'views/utility_meter_menu.xml',
        'views/utility_config_menu.xml',
        'views/utility_cron_views.xml',
        'views/utility_workflow_command_views.xml',
        'views/utility_subscriber_category_views.xml',
        'views/utility_subscriber_views.xml',
        'wizards/views/utility_period_generator_views.xml',
        'wizards/views/utility_period_adjust_wizard_views.xml',
        'views/utility_date_range_views.xml',
        'views/utility_contract_template_views.xml',
        'views/utility_contract_template_block_views.xml',
        'views/utility_contract_template_history_views.xml',
        'views/utility_contract_template_version_views.xml',
        'views/utility_settings_views.xml',
        'views/utility_notification_views.xml',
        'views/utility_integration_views.xml',
        'views/utility_res_users_views.xml',
        'views/sale_order_type_views.xml',
        'views/res_partner_sector_views.xml',
        'views/utility_res_partner_views.xml',
        'views/utility_res_company_views.xml',
        'wizards/views/transformer_balance_wizard_views.xml',
        'wizards/views/formula_test_wizard_views.xml',
        'wizards/views/utility_meter_wizard_views.xml',
        'wizards/views/utility_contract_template_clone_wizard_views.xml',
        'wizards/views/utility_route_assignment_wizard_views.xml',
        'wizards/views/utility_migration_import_wizard_views.xml',
        'data/utility_migration_actions.xml',
        'data/utility_migration_cron.xml',
        'views/utility_migration_mapping_views.xml',
        'views/utility_migration_batch_views.xml',
        'views/utility_migration_customer_views.xml',
        'views/utility_migration_feeder_views.xml',
        'views/utility_migration_transformer_views.xml',

        'report/transformer_balance_report_template.xml',
        'report/transformer_balance_report.xml',
        'report/utility_receipt_report.xml',
        'report/utility_meter_qr_report.xml',
        'report/utility_meter_qr_bulk_report.xml',
        'views/dashboard_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'assets': {
        'web.assets_backend': [
            'utility_core/static/src/scss/utility_list_layout.scss',
            'utility_core/static/lib/html5-qrcode.min.js',
            'utility_core/static/src/js/barcode_camera_widget.js',
            'utility_core/static/src/js/error_dialog_clipboard.js',
            'utility_core/static/src/xml/barcode_camera_widget.xml',
            'utility_core/static/src/css/utility_dashboard.css',
            'utility_core/static/src/js/utility_dashboard.js',
            'utility_core/static/src/xml/utility_dashboard.xml',
        ],
    },
    'sequence': 2,
}
