{
    'name': 'Utility Billing',
    'version': '16.0.2.8.0',
    'category': 'Utility ERP',
    'summary': 'Postpaid Billing & Collections Engine (Sale Order Based)',
    'description': """
Enterprise Utility Billing Module
===================================
Postpaid billing engine with meter reading management,
billing cycles, sale order generation, penalty calculation,
debt management, collections, and online payment gateway integration.
    """,
    'author': 'Utility ERP Platform',
    'website': 'https://www.utility-erp.com',
    'license': 'LGPL-3',
    'depends': ['utility_core', 'utility_operations', 'account', 'sale', 'sale_management', 'sale_stock', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'security/utility_billing_security.xml',
        'data/utility_sequence.xml',
        'data/utility_billing_account_data.xml',
        'data/utility_billing_product_data.xml',
        'data/utility_billing_defaults.xml',
        'data/utility_cron.xml',
        'data/utility_cron_extras.xml',
        'data/utility_cron_batch.xml',
        'data/utility_billing_adjustment_data.xml',
        'data/utility_penalty_type_data.xml',
        'views/utility_billing_menu.xml',
        'views/utility_transformer_loss_report_views.xml',
        'views/utility_service_charge_views.xml',
        'views/utility_reading_views.xml',
        'views/utility_meter_replacement_views.xml',
        'views/utility_reading_settlement_views.xml',
        'views/utility_reading_batch_views.xml',
        'views/utility_bill_reading_component_views.xml',
        'views/utility_bill_pricing_snapshot_views.xml',
        'views/utility_billing_adjustment_views.xml',
        'views/utility_sale_order_views.xml',
        'views/utility_sale_order_report.xml',
        'views/utility_customer_views.xml',
        'views/account_move_views.xml',
        'views/commercial_invoice_review_views.xml',
        'views/account_payment_views.xml',
        'views/utility_payment_allocation_views.xml',
        'views/utility_collection_views.xml',
        'views/utility_bank_settlement_views.xml',
        'views/account_payment_report.xml',
        'views/utility_customer_statement_views.xml',
        'views/financial_settlement_views.xml',
        'views/utility_writeoff_views.xml',
        'views/utility_deposit_views.xml',
        'views/utility_penalty_views.xml',
        'views/utility_penalty_type_views.xml',
        'views/utility_billing_settings_views.xml',
        'views/utility_payment_gateway_views.xml',
        'views/utility_portal_templates.xml',
        'views/utility_reading_review_views.xml',
    ],
    'demo': [
        'data/utility_demo.xml',
        'data/utility_billing_sample_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 2,
    'post_init_hook': 'post_init_hook',
        'assets': {
        'web.assets_backend': [
            'utility_billing/static/src/reading_review/reading_review.scss',
            'utility_billing/static/src/reading_review/components/rejection_dialog.js',
            'utility_billing/static/src/reading_review/components/rejection_dialog.xml',
            'utility_billing/static/src/reading_review/components/image_lightbox.js',
            'utility_billing/static/src/reading_review/components/image_lightbox.xml',
            'utility_billing/static/src/reading_review/components/media_image_field.js',
            'utility_billing/static/src/reading_review/components/media_image_field.xml',
            'utility_billing/static/src/reading_review/reading_review_action.js',
            'utility_billing/static/src/reading_review/reading_review_action.xml',
        ],
    },
}
