[options]
addons_path = F:\invo-system,D:\odoo-16.0\odoo-16.0\addons
data_dir = F:\invo-system\.odoo-data
db_host = localhost
db_port = 5432
db_user = odoo16
db_password = odoo16
db_name = invoice_utility_erp
dbfilter = ^invoice_utility_erp$
xmlrpc_port = 8170
admin_passwd = admin
logfile = F:\invo-system\odoo-server.log
